INSERT INTO Animal VALUES
(1, 'utilizador1@gmail.com', 'animal0', 'caesA&P.png', 'M', 'B', 'Pastor Alemao', 'P', 'Branco', 'S', 'P', NULL, 'Porto', 'C'),
(2, 'utilizador1@gmail.com', 'animal1', 'caesA&P.png', 'F', 'J', 'Lavrador', 'M', 'Preto', 'C', 'P', NULL, 'Porto', 'C'),
(3, 'utilizador1@gmail.com', 'animal2', 'caesA&P.png', 'M', 'A', 'Buldogue', 'G', 'Castanho', 'M', 'P', NULL, 'Porto', 'C'),
(4, 'utilizador1@gmail.com', 'animal3', 'caesA&P.png', 'F', 'B', 'Beagle', 'P', 'Cinzento', 'L', 'P', NULL, 'Porto', 'C'),
(5, 'utilizador1@gmail.com', 'animal4', 'caesA&P.png', 'M', 'J', 'Poodle', 'M', 'Bege', 'S', 'P', NULL, 'Porto', 'C'),
(6, 'utilizador1@gmail.com', 'animal5', 'caesA&P.png', 'F', 'A', 'Rottwiller', 'G', 'Branco', 'C', 'P', NULL, 'Porto', 'C'),
(7, 'utilizador1@gmail.com', 'animal6', 'caesA&P.png', 'M', 'B', 'Golden Retriver', 'P', 'Preto', 'M', 'P', NULL, 'Porto', 'C'),
(8, 'utilizador1@gmail.com', 'animal7', 'caesA&P.png', 'F', 'J', 'Pastor Alemao', 'M', 'Castanho', 'L', 'P', NULL, 'Porto', 'C'),
(9, 'utilizador1@gmail.com', 'animal8', 'caesA&P.png', 'M', 'A', 'Lavrador', 'G', 'Cinzento', 'S', 'P', NULL, 'Porto', 'C'),
(10, 'utilizador1@gmail.com', 'animal9', 'caesA&P.png', 'F', 'B', 'Buldogue', 'P', 'Preto', 'C', 'P', NULL, 'Porto', 'C'),
(11, 'utilizador2@gmail.com', 'animal10', 'caesA&P.png', 'M', 'J', 'Beagle', 'M', 'Cinzento', 'M', 'P', NULL, 'Braga', 'C'),
(12, 'utilizador2@gmail.com', 'animal12', 'caesA&P.png', 'F', 'A', 'Poodle', 'G', 'Castanho', 'L', 'P', NULL, 'Braga', 'C'),
(13, 'utilizador2@gmail.com', 'animal11', 'caesA&P.png', 'M', 'B', 'Golden Retriver', 'P', 'Branco', 'S', 'P', NULL, 'Braga', 'C'),
(14, 'utilizador2@gmail.com', 'animal13', 'caesA&P.png', 'F', 'J', 'Pastor Alemao', 'M', 'Preto', 'C', 'P', NULL, 'Braga', 'C'),
(15, 'utilizador2@gmail.com', 'animal14', 'caesA&P.png', 'M', 'A', 'Lavrador', 'G', 'Bege', 'M', 'P', NULL, 'Braga', 'C'),
(16, 'utilizador2@gmail.com', 'animal15', 'caesA&P.png', 'F', 'B', 'Buldogue', 'P', 'Bege', 'L', 'P', NULL, 'Braga', 'C'),
(17, 'utilizador2@gmail.com', 'animal16', 'caesA&P.png', 'M', 'J', 'Poodle', 'M', 'Preto', 'S', 'P', NULL, 'Braga', 'C'),
(18, 'utilizador2@gmail.com', 'animal17', 'caesA&P.png', 'F', 'A', 'Beagle', 'G', 'Branco', 'C', 'P', NULL, 'Braga', 'C'),
(19, 'utilizador2@gmail.com', 'animal18', 'caesA&P.png', 'M', 'B', 'Rottweiller', 'P', 'Castanho', 'M', 'P', NULL, 'Braga', 'C'),
(20, 'utilizador2@gmail.com', 'animal19', 'caesA&P.png', 'F', 'J', 'Golden Retriver', 'M', 'Bege', 'L', 'P', NULL, 'Braga', 'C'),
(21, 'utilizador3@gmail.com', 'animal20', 'caesA&P.png', 'M', 'A', 'Beagle', 'M', 'Cinzento', 'S', 'P', NULL, 'Lisboa', 'C'),
(22, 'utilizador3@gmail.com', 'animal21', 'caesA&P.png', 'F', 'B', 'Lavrador', 'G', 'Bege', 'C', 'P', NULL, 'Lisboa', 'C'),
(23, 'utilizador3@gmail.com', 'animal22', 'caesA&P.png', 'M', 'J', 'Buldogue', 'P', 'Preto', 'M', 'P', NULL, 'Lisboa', 'C'),
(24, 'utilizador3@gmail.com', 'animal23', 'caesA&P.png', 'F', 'A', 'Pastor Alemao', 'M', 'Branco', 'L', 'P', NULL, 'Lisboa', 'C'),
(25, 'utilizador3@gmail.com', 'animal24', 'caesA&P.png', 'M', 'B', 'Poodle', 'G', 'Bege', 'S', 'P', NULL, 'Lisboa', 'C'),
(26, 'utilizador3@gmail.com', 'animal25', 'caesA&P.png', 'F', 'J', 'Golden Retriver', 'P', 'Preto', 'C', 'P', NULL, 'Lisboa', 'C'),
(27, 'utilizador3@gmail.com', 'animal26', 'caesA&P.png', 'M', 'A', 'Beagle', 'M', 'Preto', 'M', 'P', NULL, 'Lisboa', 'C'),
(28, 'utilizador3@gmail.com', 'animal27', 'caesA&P.png', 'F', 'B', 'Lavrador', 'G', 'Bege', 'L', 'P', NULL, 'Lisboa', 'C'),
(29, 'utilizador3@gmail.com', 'animal28', 'caesA&P.png', 'M', 'J', 'Pastor Alemao', 'P', 'Castanho', 'S', 'P', NULL, 'Lisboa', 'C'),
(30, 'utilizador3@gmail.com', 'animal29', 'caesA&P.png', 'F', 'A', 'Beagle', 'M', 'Preto', 'C', 'P', NULL, 'Lisboa', 'C'),
(31, 'utilizador4@gmail.com', 'animal30', 'caesA&P.png', 'M', 'B', 'Outro', 'G', 'Branco', 'M', 'P', NULL, 'Faro', 'C'),
(32, 'utilizador4@gmail.com', 'animal31', 'caesA&P.png', 'F', 'J', 'Pastor Alemao', 'P', 'Branco', 'S', 'P', NULL, 'Faro', 'C'),
(33, 'utilizador4@gmail.com', 'animal32', 'caesA&P.png', 'M', 'A', 'Lavrador', 'M', 'Bege', 'C', 'P', NULL, 'Faro', 'C'),
(34, 'utilizador4@gmail.com', 'animal33', 'caesA&P.png', 'F', 'B', 'Buldogue', 'G', 'Preto', 'M', 'P', NULL, 'Faro', 'C'),
(35, 'utilizador4@gmail.com', 'animal34', 'caesA&P.png', 'M', 'J', 'Poodle', 'P', 'Castanho', 'L', 'P', NULL, 'Faro', 'C'),
(36, 'utilizador4@gmail.com', 'animal35', 'caesA&P.png', 'F', 'A', 'Beagle', 'M', 'Cinzento', 'S', 'P', NULL, 'Faro', 'C'),
(37, 'utilizador4@gmail.com', 'animal36', 'caesA&P.png', 'M', 'B', 'Rottwiller', 'G', 'Indefinido', 'C', 'P', NULL, 'Faro', 'C'),
(38, 'utilizador4@gmail.com', 'animal37', 'caesA&P.png', 'F', 'J', 'Golden Retriever', 'P', 'Branco', 'M', 'P', NULL, 'Faro', 'C'),
(39, 'utilizador4@gmail.com', 'animal38', 'caesA&P.png', 'M', 'A', 'Pastor Alemao', 'M', 'Bege', 'L', 'P', NULL, 'Faro', 'C'),
(40, 'utilizador4@gmail.com', 'animal39', 'caesA&P.png', 'F', 'B', 'Lavrador', 'G', 'Preto', 'S', 'P', NULL, 'Faro', 'C'),
(41, 'utilizador5@gmail.com', 'animal40', 'caesA&P.png', 'M', 'J', 'Buldogue', 'P', 'Castanho', 'C', 'P', NULL, 'Coimbra', 'C'),
(42, 'utilizador5@gmail.com', 'animal41', 'caesA&P.png', 'F', 'A', 'Poodle', 'M', 'Cinzento', 'M', 'P', NULL, 'Coimbra', 'C'),
(43, 'utilizador5@gmail.com', 'animal42', 'caesA&P.png', 'M', 'B', 'Beagle', 'G', 'Indefinido', 'L', 'P', NULL, 'Coimbra', 'C'),
(44, 'utilizador5@gmail.com', 'animal43', 'caesA&P.png', 'F', 'J', 'Rottwiller', 'P', 'Branco', 'S', 'P', NULL, 'Coimbra', 'C'),
(45, 'utilizador5@gmail.com', 'animal44', 'caesA&P.png', 'M', 'A', 'Golden Retriever', 'M', 'Bege', 'C', 'P', NULL, 'Coimbra', 'C'),
(46, 'utilizador5@gmail.com', 'animal45', 'caesA&P.png', 'F', 'B', 'Pastor Alemao', 'G', 'Preto', 'M', 'P', NULL, 'Coimbra', 'C'),
(47, 'utilizador5@gmail.com', 'animal46', 'caesA&P.png', 'M', 'J', 'Lavrador', 'P', 'Castanho', 'L', 'P', NULL, 'Coimbra', 'C'),
(48, 'utilizador5@gmail.com', 'animal47', 'caesA&P.png', 'F', 'A', 'Buldogue', 'M', 'Cinzento', 'S', 'P', NULL, 'Coimbra', 'C'),
(49, 'utilizador5@gmail.com', 'animal48', 'caesA&P.png', 'M', 'B', 'Poodle', 'G', 'Indefinido', 'C', 'P', NULL, 'Coimbra', 'C'),
(50, 'utilizador5@gmail.com', 'animal49', 'caesA&P.png', 'F', 'J', 'Beagle', 'P', 'Branco', 'M', 'P', NULL, 'Coimbra', 'C'),
(51, 'utilizador500@gmail.com', 'animal50', 'caesA&P.png', 'M', 'A', 'Rottwiller', 'M', 'Bege', 'L', 'E', NULL, NULL, 'C'),
(52, 'utilizador500@gmail.com', 'animal51', 'caesA&P.png', 'F', 'B', 'Golden Retriever', 'G', 'Preto', 'S', 'E', NULL, NULL, 'C'),
(53, 'utilizador500@gmail.com', 'animal52', 'caesA&P.png', 'M', 'J', 'Pastor Alemao', 'P', 'Castanho', 'C', 'E', NULL, NULL, 'C'),
(54, 'utilizador500@gmail.com', 'animal53', 'caesA&P.png', 'F', 'A', 'Lavrador', 'M', 'Cinzento', 'M', 'E', NULL, NULL, 'C'),
(55, 'utilizador500@gmail.com', 'animal54', 'caesA&P.png', 'M', 'B', 'Buldogue', 'G', 'Indefinido', 'L', 'E', NULL, NULL, 'C'),
(56, 'utilizador500@gmail.com', 'animal55', 'caesA&P.png', 'F', 'J', 'Poodle', 'P', 'Branco', 'S', 'E', NULL, NULL, 'C'),
(57, 'utilizador500@gmail.com', 'animal56', 'caesA&P.png', 'M', 'A', 'Beagle', 'M', 'Bege', 'C', 'E', NULL, NULL, 'C'),
(58, 'utilizador500@gmail.com', 'animal57', 'caesA&P.png', 'F', 'B', 'Rottwiller', 'G', 'Preto', 'M', 'E', NULL, NULL, 'C'),
(59, 'utilizador500@gmail.com', 'animal58', 'caesA&P.png', 'M', 'J', 'Golden Retriever', 'P', 'Castanho', 'L', 'E', NULL, NULL, 'C'),
(60, 'utilizador500@gmail.com', 'animal59', 'caesA&P.png', 'F', 'A', 'Pastor Alemao', 'M', 'Cinzento', 'S', 'E', NULL, NULL, 'C'),
(61, 'utilizador501@gmail.com', 'animal60', 'caesA&P.png', 'M', 'B', 'Lavrador', 'G', 'Indefinido', 'C', 'E', NULL, NULL, 'C'),
(62, 'utilizador501@gmail.com', 'animal61', 'caesA&P.png', 'F', 'J', 'Buldogue', 'P', 'Branco', 'M', 'E', NULL, NULL, 'C'),
(63, 'utilizador501@gmail.com', 'animal62', 'caesA&P.png', 'M', 'A', 'Poodle', 'M', 'Bege', 'L', 'E', NULL, NULL, 'C'),
(64, 'utilizador501@gmail.com', 'animal63', 'caesA&P.png', 'F', 'B', 'Beagle', 'G', 'Preto', 'S', 'E', NULL, NULL, 'C'),
(65, 'utilizador501@gmail.com', 'animal64', 'caesA&P.png', 'M', 'J', 'Rottwiller', 'P', 'Castanho', 'C', 'E', NULL, NULL, 'C'),
(66, 'utilizador501@gmail.com', 'animal65', 'caesA&P.png', 'F', 'A', 'Golden Retriever', 'M', 'Cinzento', 'M', 'E', NULL, NULL, 'C'),
(67, 'utilizador501@gmail.com', 'animal66', 'caesA&P.png', 'M', 'B', 'Pastor Alemao', 'G', 'Indefinido', 'L', 'E', NULL, NULL, 'C'),
(68, 'utilizador501@gmail.com', 'animal67', 'caesA&P.png', 'F', 'J', 'Lavrador', 'P', 'Branco', 'S', 'E', NULL, NULL, 'C'),
(69, 'utilizador501@gmail.com', 'animal68', 'caesA&P.png', 'M', 'A', 'Buldogue', 'M', 'Bege', 'C', 'E', NULL, NULL, 'C'),
(70, 'utilizador501@gmail.com', 'animal69', 'caesA&P.png', 'F', 'B', 'Poodle', 'G', 'Preto', 'M', 'E', NULL, NULL, 'C'),
(71, 'utilizador502@gmail.com', 'animal70', 'caesA&P.png', 'M', 'J', 'Beagle', 'P', 'Castanho', 'L', 'E', NULL, NULL, 'C'),
(72, 'utilizador502@gmail.com', 'animal71', 'caesA&P.png', 'F', 'A', 'Rottwiller', 'M', 'Cinzento', 'S', 'E', NULL, NULL, 'C'),
(73, 'utilizador502@gmail.com', 'animal72', 'caesA&P.png', 'M', 'B', 'Golden Retriever', 'G', 'Indefinido', 'C', 'E', NULL, NULL, 'C'),
(74, 'utilizador502@gmail.com', 'animal73', 'caesA&P.png', 'F', 'J', 'Pastor Alemao', 'P', 'Branco', 'M', 'E', NULL, NULL, 'C'),
(75, 'utilizador502@gmail.com', 'animal74', 'caesA&P.png', 'M', 'A', 'Lavrador', 'M', 'Bege', 'L', 'E', NULL, NULL, 'C'),
(76, 'utilizador502@gmail.com', 'animal75', 'caesA&P.png', 'F', 'B', 'Buldogue', 'G', 'Preto', 'S', 'E', NULL, NULL, 'C'),
(77, 'utilizador502@gmail.com', 'animal76', 'caesA&P.png', 'M', 'J', 'Poodle', 'P', 'Castanho', 'C', 'E', NULL, NULL, 'C'),
(78, 'utilizador502@gmail.com', 'animal77', 'caesA&P.png', 'F', 'A', 'Beagle', 'M', 'Cinzento', 'M', 'E', NULL, NULL, 'C'),
(79, 'utilizador502@gmail.com', 'animal78', 'caesA&P.png', 'M', 'B', 'Rottwiller', 'G', 'Indefinido', 'L', 'E', NULL, NULL, 'C'),
(80, 'utilizador502@gmail.com', 'animal79', 'caesA&P.png', 'F', 'J', 'Golden Retriever', 'P', 'Branco', 'S', 'E', NULL, NULL, 'C'),
(81, 'utilizador503@gmail.com', 'animal80', 'caesA&P.png', 'M', 'A', 'Pastor Alemao', 'M', 'Bege', 'C', 'E', NULL, NULL, 'C'),
(82, 'utilizador503@gmail.com', 'animal81', 'caesA&P.png', 'F', 'B', 'Lavrador', 'G', 'Preto', 'M', 'E', NULL, NULL, 'C'),
(83, 'utilizador503@gmail.com', 'animal82', 'caesA&P.png', 'M', 'J', 'Buldogue', 'P', 'Castanho', 'L', 'E', NULL, NULL, 'C'),
(84, 'utilizador503@gmail.com', 'animal83', 'caesA&P.png', 'F', 'A', 'Poodle', 'M', 'Cinzento', 'S', 'E', NULL, NULL, 'C'),
(85, 'utilizador503@gmail.com', 'animal84', 'caesA&P.png', 'M', 'B', 'Beagle', 'G', 'Indefinido', 'C', 'E', NULL, NULL, 'C'),
(86, 'utilizador503@gmail.com', 'animal85', 'caesA&P.png', 'F', 'J', 'Rottwiller', 'P', 'Branco', 'M', 'E', NULL, NULL, 'C'),
(87, 'utilizador503@gmail.com', 'animal86', 'caesA&P.png', 'M', 'A', 'Golden Retriever', 'M', 'Bege', 'L', 'E', NULL, NULL, 'C'),
(88, 'utilizador503@gmail.com', 'animal87', 'caesA&P.png', 'F', 'B', 'Pastor Alemao', 'G', 'Preto', 'S', 'E', NULL, NULL, 'C'),
(89, 'utilizador503@gmail.com', 'animal88', 'caesA&P.png', 'M', 'J', 'Lavrador', 'P', 'Castanho', 'C', 'E', NULL, NULL, 'C'),
(90, 'utilizador503@gmail.com', 'animal89', 'caesA&P.png', 'M', 'A', 'Buldogue', 'M', 'Cinzento', 'M', 'E', NULL, NULL, 'C'),
(91, 'utilizador504@gmail.com', 'animal90', 'caesA&P.png', 'F', 'B', 'Poodle', 'G', 'Indefinido', 'L', 'E', NULL, NULL, 'C'),
(92, 'utilizador504@gmail.com', 'animal91', 'caesA&P.png', 'M', 'J', 'Beagle', 'P', 'Branco', 'S', 'E', NULL, NULL, 'C'),
(93, 'utilizador504@gmail.com', 'animal92', 'caesA&P.png', 'F', 'A', 'Rottwiller', 'M', 'Bege', 'C', 'E', NULL, NULL, 'C'),
(94, 'utilizador504@gmail.com', 'animal93', 'caesA&P.png', 'M', 'B', 'Golden Retriever', 'G', 'Preto', 'M', 'E', NULL, NULL, 'C'),
(95, 'utilizador504@gmail.com', 'animal94', 'caesA&P.png', 'F', 'J', 'Pastor Alemao', 'P', 'Castanho', 'S', 'E', NULL, NULL, 'C'),
(96, 'utilizador504@gmail.com', 'animal95', 'caesA&P.png', 'M', 'A', 'Lavrador', 'M', 'Cinzento', 'C', 'E', NULL, NULL, 'C'),
(97, 'utilizador504@gmail.com', 'animal96', 'caesA&P.png', 'F', 'B', 'Buldogue', 'G', 'Indefinido', 'M', 'E', NULL, NULL, 'C'),
(98, 'utilizador504@gmail.com', 'animal97', 'caesA&P.png', 'M', 'J', 'Poodle', 'P', 'Branco', 'L', 'E', NULL, NULL, 'C'),
(99, 'utilizador504@gmail.com', 'animal98', 'caesA&P.png', 'F', 'A', 'Beagle', 'M', 'Bege', 'S', 'E', NULL, NULL, 'C'),
(100, 'utilizador504@gmail.com', 'animal99', 'caesA&P.png', 'M', 'B', 'Rottwiller', 'G', 'Preto', 'C', 'E', NULL, NULL, 'C'),
(101, 'utilizador505@gmail.com', 'animal100', 'gatosA&P.png', 'M', 'B', 'Persa', 'P', 'Branco', 'S', 'E', NULL, NULL, 'G'),
(102, 'utilizador505@gmail.com', 'animal101', 'gatosA&P.png', 'F', 'J', 'Siames', 'M', 'Bege', 'C', 'E', NULL, NULL, 'G'),
(103, 'utilizador505@gmail.com', 'animal102', 'gatosA&P.png', 'M', 'A', 'Ragdoll', 'G', 'Preto', 'M', 'E', NULL, NULL, 'G'),
(104, 'utilizador505@gmail.com', 'animal103', 'gatosA&P.png', 'F', 'B', 'ScottishFold', 'I', 'Cinzento', 'L', 'E', NULL, NULL, 'G'),
(105, 'utilizador505@gmail.com', 'animal104', 'gatosA&P.png', 'M', 'J', 'Outro', 'P', 'Laranja', 'S', 'E', NULL, NULL, 'G'),
(106, 'utilizador505@gmail.com', 'animal105', 'gatosA&P.png', 'F', 'A', 'Persa', 'M', 'Indefinido', 'C', 'E', NULL, NULL, 'G'),
(107, 'utilizador505@gmail.com', 'animal106', 'gatosA&P.png', 'M', 'B', 'Siames', 'G', 'Branco', 'M', 'E', NULL, NULL, 'G'),
(108, 'utilizador505@gmail.com', 'animal107', 'gatosA&P.png', 'F', 'J', 'Ragdoll', 'I', 'Bege', 'L', 'E', NULL, NULL, 'G'),
(109, 'utilizador505@gmail.com', 'animal108', 'gatosA&P.png', 'M', 'A', 'ScottishFold', 'P', 'Preto', 'S', 'E', NULL, NULL, 'G'),
(110, 'utilizador505@gmail.com', 'animal109', 'gatosA&P.png', 'F', 'B', 'Outro', 'M', 'Cinzento', 'C', 'E', NULL, NULL, 'G'),
(111, 'utilizador506@gmail.com', 'animal110', 'gatosA&P.png', 'M', 'J', 'Persa', 'G', 'Laranja', 'M', 'E', NULL, NULL, 'G'),
(112, 'utilizador506@gmail.com', 'animal111', 'gatosA&P.png', 'F', 'A', 'Siames', 'I', 'Indefinido', 'L', 'E', NULL, NULL, 'G'),
(113, 'utilizador506@gmail.com', 'animal112', 'gatosA&P.png', 'M', 'B', 'Ragdoll', 'P', 'Branco', 'S', 'E', NULL, NULL, 'G'),
(114, 'utilizador506@gmail.com', 'animal113', 'gatosA&P.png', 'F', 'J', 'ScottishFold', 'M', 'Bege', 'C', 'E', NULL, NULL, 'G'),
(115, 'utilizador506@gmail.com', 'animal114', 'gatosA&P.png', 'M', 'A', 'Outro', 'G', 'Preto', 'M', 'E', NULL, NULL, 'G'),
(116, 'utilizador506@gmail.com', 'animal115', 'gatosA&P.png', 'F', 'B', 'Persa', 'I', 'Cinzento', 'L', 'E', NULL, NULL, 'G'),
(117, 'utilizador506@gmail.com', 'animal116', 'gatosA&P.png', 'M', 'J', 'Siames', 'P', 'Laranja', 'S', 'E', NULL, NULL, 'G'),
(118, 'utilizador506@gmail.com', 'animal117', 'gatosA&P.png', 'F', 'A', 'Ragdoll', 'M', 'Indefinido', 'C', 'E', NULL, NULL, 'G'),
(119, 'utilizador506@gmail.com', 'animal118', 'gatosA&P.png', 'M', 'B', 'ScottishFold', 'G', 'Branco', 'M', 'E', NULL, NULL, 'G'),
(120, 'utilizador506@gmail.com', 'animal119', 'gatosA&P.png', 'F', 'J', 'Outro', 'I', 'Bege', 'L', 'E', NULL, NULL, 'G'),
(121, 'utilizador507@gmail.com', 'animal120', 'gatosA&P.png', 'M', 'A', 'Persa', 'P', 'Preto', 'S', 'E', NULL, NULL, 'G'),
(122, 'utilizador507@gmail.com', 'animal121', 'gatosA&P.png', 'F', 'B', 'Siames', 'M', 'Cinzento', 'C', 'E', NULL, NULL, 'G'),
(123, 'utilizador507@gmail.com', 'animal122', 'gatosA&P.png', 'M', 'J', 'Ragdoll', 'G', 'Laranja', 'M', 'E', NULL, NULL, 'G'),
(124, 'utilizador507@gmail.com', 'animal123', 'gatosA&P.png', 'F', 'A', 'ScottishFold', 'I', 'Indefinido', 'L', 'E', NULL, NULL, 'G'),
(125, 'utilizador507@gmail.com', 'animal124', 'gatosA&P.png', 'M', 'B', 'Outro', 'P', 'Branco', 'S', 'E', NULL, NULL, 'G'),
(126, 'utilizador507@gmail.com', 'animal125', 'gatosA&P.png', 'F', 'J', 'Persa', 'M', 'Bege', 'C', 'E', NULL, NULL, 'G'),
(127, 'utilizador507@gmail.com', 'animal126', 'gatosA&P.png', 'M', 'A', 'Siames', 'G', 'Preto', 'M', 'E', NULL, NULL, 'G'),
(128, 'utilizador507@gmail.com', 'animal127', 'gatosA&P.png', 'F', 'B', 'Ragdoll', 'I', 'Cinzento', 'L', 'E', NULL, NULL, 'G'),
(129, 'utilizador507@gmail.com', 'animal128', 'gatosA&P.png', 'M', 'J', 'ScottishFold', 'P', 'Laranja', 'S', 'E', NULL, NULL, 'G'),
(130, 'utilizador507@gmail.com', 'animal129', 'gatosA&P.png', 'F', 'A', 'Outro', 'M', 'Indefinido', 'C', 'E', NULL, NULL, 'G'),
(131, 'utilizador508@gmail.com', 'animal130', 'gatosA&P.png', 'M', 'B', 'Persa', 'G', 'Branco', 'M', 'E', NULL, NULL, 'G'),
(132, 'utilizador508@gmail.com', 'animal131', 'gatosA&P.png', 'F', 'J', 'Siames', 'I', 'Bege', 'L', 'E', NULL, NULL, 'G'),
(133, 'utilizador508@gmail.com', 'animal132', 'gatosA&P.png', 'M', 'A', 'Ragdoll', 'P', 'Preto', 'S', 'E', NULL, NULL, 'G'),
(134, 'utilizador508@gmail.com', 'animal133', 'gatosA&P.png', 'F', 'B', 'ScottishFold', 'M', 'Cinzento', 'C', 'E', NULL, NULL, 'G'),
(135, 'utilizador508@gmail.com', 'animal134', 'gatosA&P.png', 'M', 'J', 'Outro', 'G', 'Laranja', 'M', 'E', NULL, NULL, 'G'),
(136, 'utilizador508@gmail.com', 'animal135', 'gatosA&P.png', 'F', 'A', 'Persa', 'I', 'Indefinido', 'L', 'E', NULL, NULL, 'G'),
(137, 'utilizador508@gmail.com', 'animal136', 'gatosA&P.png', 'M', 'B', 'Siames', 'P', 'Branco', 'S', 'E', NULL, NULL, 'G'),
(138, 'utilizador508@gmail.com', 'animal137', 'gatosA&P.png', 'F', 'J', 'Ragdoll', 'M', 'Bege', 'C', 'E', NULL, NULL, 'G'),
(139, 'utilizador508@gmail.com', 'animal138', 'gatosA&P.png', 'M', 'A', 'ScottishFold', 'G', 'Preto', 'M', 'E', NULL, NULL, 'G'),
(140, 'utilizador508@gmail.com', 'animal139', 'gatosA&P.png', 'F', 'B', 'Outro', 'I', 'Cinzento', 'L', 'E', NULL, NULL, 'G'),
(141, 'utilizador509@gmail.com', 'animal140', 'gatosA&P.png', 'M', 'J', 'Persa', 'P', 'Laranja', 'S', 'E', NULL, NULL, 'G'),
(142, 'utilizador509@gmail.com', 'animal141', 'gatosA&P.png', 'F', 'A', 'Siames', 'M', 'Indefinido', 'C', 'E', NULL, NULL, 'G'),
(143, 'utilizador509@gmail.com', 'animal142', 'gatosA&P.png', 'M', 'B', 'Ragdoll', 'G', 'Branco', 'M', 'E', NULL, NULL, 'G'),
(144, 'utilizador509@gmail.com', 'animal143', 'gatosA&P.png', 'F', 'J', 'ScottishFold', 'I', 'Bege', 'L', 'E', NULL, NULL, 'G'),
(145, 'utilizador509@gmail.com', 'animal144', 'gatosA&P.png', 'M', 'A', 'Outro', 'P', 'Preto', 'S', 'E', NULL, NULL, 'G'),
(146, 'utilizador509@gmail.com', 'animal145', 'gatosA&P.png', 'F', 'B', 'Persa', 'M', 'Cinzento', 'C', 'E', NULL, NULL, 'G'),
(147, 'utilizador509@gmail.com', 'animal146', 'gatosA&P.png', 'M', 'J', 'Siames', 'G', 'Laranja', 'M', 'E', NULL, NULL, 'G'),
(148, 'utilizador509@gmail.com', 'animal147', 'gatosA&P.png', 'F', 'A', 'Ragdoll', 'I', 'Indefinido', 'L', 'E', NULL, NULL, 'G'),
(149, 'utilizador509@gmail.com', 'animal148', 'gatosA&P.png', 'M', 'B', 'ScottishFold', 'P', 'Branco', 'S', 'E', NULL, NULL, 'G'),
(150, 'utilizador509@gmail.com', 'animal149', 'gatosA&P.png', 'F', 'J', 'Outro', 'M', 'Bege', 'C', 'E', NULL, NULL, 'G'),
(151, 'utilizador510@gmail.com', 'animal150', 'gatosA&P.png', 'M', 'A', 'Persa', 'G', 'Preto', 'M', 'E', NULL, NULL, 'G'),
(152, 'utilizador510@gmail.com', 'animal151', 'gatosA&P.png', 'F', 'B', 'Siames', 'I', 'Cinzento', 'L', 'E', NULL, NULL, 'G'),
(153, 'utilizador510@gmail.com', 'animal152', 'gatosA&P.png', 'M', 'J', 'Ragdoll', 'P', 'Laranja', 'S', 'E', NULL, NULL, 'G'),
(154, 'utilizador510@gmail.com', 'animal153', 'gatosA&P.png', 'F', 'A', 'ScottishFold', 'M', 'Indefinido', 'C', 'E', NULL, NULL, 'G'),
(155, 'utilizador510@gmail.com', 'animal154', 'gatosA&P.png', 'M', 'B', 'Outro', 'G', 'Branco', 'M', 'E', NULL, NULL, 'G'),
(156, 'utilizador510@gmail.com', 'animal155', 'gatosA&P.png', 'F', 'J', 'Persa', 'I', 'Bege', 'L', 'E', NULL, NULL, 'G'),
(157, 'utilizador510@gmail.com', 'animal156', 'gatosA&P.png', 'M', 'A', 'Siames', 'P', 'Preto', 'S', 'E', NULL, NULL, 'G'),
(158, 'utilizador510@gmail.com', 'animal157', 'gatosA&P.png', 'F', 'B', 'Ragdoll', 'M', 'Cinzento', 'C', 'E', NULL, NULL, 'G'),
(159, 'utilizador510@gmail.com', 'animal158', 'gatosA&P.png', 'M', 'J', 'ScottishFold', 'G', 'Laranja', 'M', 'E', NULL, NULL, 'G'),
(160, 'utilizador510@gmail.com', 'animal159', 'gatosA&P.png', 'F', 'A', 'Outro', 'I', 'Indefinido', 'L', 'E', NULL, NULL, 'G'),
(161, 'utilizador511@gmail.com', 'animal160', 'gatosA&P.png', 'M', 'B', 'Persa', 'P', 'Branco', 'S', 'E', NULL, NULL, 'G'),
(162, 'utilizador511@gmail.com', 'animal161', 'gatosA&P.png', 'F', 'J', 'Siames', 'M', 'Bege', 'C', 'E', NULL, NULL, 'G'),
(163, 'utilizador511@gmail.com', 'animal162', 'gatosA&P.png', 'M', 'A', 'Ragdoll', 'G', 'Preto', 'M', 'E', NULL, NULL, 'G'),
(164, 'utilizador511@gmail.com', 'animal163', 'gatosA&P.png', 'F', 'B', 'ScottishFold', 'I', 'Cinzento', 'L', 'E', NULL, NULL, 'G'),
(165, 'utilizador511@gmail.com', 'animal164', 'gatosA&P.png', 'M', 'J', 'Outro', 'P', 'Laranja', 'S', 'E', NULL, NULL, 'G'),
(166, 'utilizador511@gmail.com', 'animal165', 'gatosA&P.png', 'F', 'A', 'Persa', 'M', 'Indefinido', 'C', 'E', NULL, NULL, 'G'),
(167, 'utilizador511@gmail.com', 'animal166', 'gatosA&P.png', 'M', 'B', 'Siames', 'G', 'Branco', 'M', 'E', NULL, NULL, 'G'),
(168, 'utilizador511@gmail.com', 'animal167', 'gatosA&P.png', 'F', 'J', 'Ragdoll', 'I', 'Bege', 'L', 'E', NULL, NULL, 'G'),
(169, 'utilizador511@gmail.com', 'animal168', 'gatosA&P.png', 'M', 'A', 'ScottishFold', 'P', 'Preto', 'S', 'E', NULL, NULL, 'G'),
(170, 'utilizador511@gmail.com', 'animal169', 'gatosA&P.png', 'F', 'B', 'Outro', 'M', 'Cinzento', 'C', 'E', NULL, NULL, 'G'),
(171, 'utilizador512@gmail.com', 'animal170', 'gatosA&P.png', 'M', 'J', 'Persa', 'G', 'Laranja', 'M', 'E', NULL, NULL, 'G'),
(172, 'utilizador512@gmail.com', 'animal171', 'gatosA&P.png', 'F', 'A', 'Siames', 'I', 'Indefinido', 'L', 'E', NULL, NULL, 'G'),
(173, 'utilizador512@gmail.com', 'animal172', 'gatosA&P.png', 'M', 'B', 'Ragdoll', 'P', 'Branco', 'S', 'E', NULL, NULL, 'G'),
(174, 'utilizador512@gmail.com', 'animal173', 'gatosA&P.png', 'F', 'J', 'ScottishFold', 'M', 'Bege', 'C', 'E', NULL, NULL, 'G'),
(175, 'utilizador512@gmail.com', 'animal174', 'gatosA&P.png', 'M', 'A', 'Outro', 'G', 'Preto', 'M', 'E', NULL, NULL, 'G'),
(176, 'utilizador512@gmail.com', 'animal175', 'gatosA&P.png', 'F', 'B', 'Persa', 'I', 'Cinzento', 'L', 'E', NULL, NULL, 'G'),
(177, 'utilizador512@gmail.com', 'animal176', 'gatosA&P.png', 'M', 'J', 'Siames', 'P', 'Laranja', 'S', 'E', NULL, NULL, 'G'),
(178, 'utilizador512@gmail.com', 'animal177', 'gatosA&P.png', 'F', 'A', 'Ragdoll', 'M', 'Indefinido', 'C', 'E', NULL, NULL, 'G'),
(179, 'utilizador512@gmail.com', 'animal178', 'gatosA&P.png', 'M', 'B', 'ScottishFold', 'G', 'Branco', 'M', 'E', NULL, NULL, 'G'),
(180, 'utilizador512@gmail.com', 'animal179', 'gatosA&P.png', 'F', 'J', 'Outro', 'I', 'Bege', 'L', 'E', NULL, NULL, 'G'),
(181, 'utilizador513@gmail.com', 'animal180', 'gatosA&P.png', 'M', 'A', 'Persa', 'P', 'Preto', 'S', 'E', NULL, NULL, 'G'),
(182, 'utilizador513@gmail.com', 'animal181', 'gatosA&P.png', 'F', 'B', 'Siames', 'M', 'Cinzento', 'C', 'E', NULL, NULL, 'G'),
(183, 'utilizador513@gmail.com', 'animal182', 'gatosA&P.png', 'M', 'J', 'Ragdoll', 'G', 'Laranja', 'M', 'E', NULL, NULL, 'G'),
(184, 'utilizador513@gmail.com', 'animal183', 'gatosA&P.png', 'F', 'A', 'ScottishFold', 'I', 'Indefinido', 'L', 'E', NULL, NULL, 'G'),
(185, 'utilizador513@gmail.com', 'animal184', 'gatosA&P.png', 'M', 'B', 'Outro', 'P', 'Branco', 'S', 'E', NULL, NULL, 'G'),
(186, 'utilizador513@gmail.com', 'animal185', 'gatosA&P.png', 'F', 'J', 'Persa', 'M', 'Bege', 'C', 'E', NULL, NULL, 'G'),
(187, 'utilizador513@gmail.com', 'animal186', 'gatosA&P.png', 'M', 'A', 'Siames', 'G', 'Preto', 'M', 'E', NULL, NULL, 'G'),
(188, 'utilizador513@gmail.com', 'animal187', 'gatosA&P.png', 'F', 'B', 'Ragdoll', 'I', 'Cinzento', 'L', 'E', NULL, NULL, 'G'),
(189, 'utilizador513@gmail.com', 'animal188', 'gatosA&P.png', 'M', 'J', 'ScottishFold', 'P', 'Laranja', 'S', 'E', NULL, NULL, 'G'),
(190, 'utilizador513@gmail.com', 'animal189', 'gatosA&P.png', 'F', 'A', 'Outro', 'M', 'Indefinido', 'C', 'E', NULL, NULL, 'G'),
(191, 'utilizador514@gmail.com', 'animal190', 'gatosA&P.png', 'M', 'B', 'Persa', 'G', 'Branco', 'M', 'E', NULL, NULL, 'G'),
(192, 'utilizador514@gmail.com', 'animal191', 'gatosA&P.png', 'F', 'J', 'Siames', 'I', 'Bege', 'L', 'E', NULL, NULL, 'G'),
(193, 'utilizador514@gmail.com', 'animal192', 'gatosA&P.png', 'M', 'A', 'Ragdoll', 'P', 'Preto', 'S', 'E', NULL, NULL, 'G'),
(194, 'utilizador514@gmail.com', 'animal193', 'gatosA&P.png', 'F', 'B', 'ScottishFold', 'M', 'Cinzento', 'C', 'E', NULL, NULL, 'G'),
(195, 'utilizador514@gmail.com', 'animal194', 'gatosA&P.png', 'M', 'J', 'Outro', 'G', 'Laranja', 'M', 'E', NULL, NULL, 'G'),
(196, 'utilizador514@gmail.com', 'animal195', 'gatosA&P.png', 'F', 'A', 'Persa', 'I', 'Indefinido', 'L', 'E', NULL, NULL, 'G'),
(197, 'utilizador514@gmail.com', 'animal196', 'gatosA&P.png', 'M', 'B', 'Siames', 'P', 'Branco', 'S', 'E', NULL, NULL, 'G'),
(198, 'utilizador514@gmail.com', 'animal197', 'gatosA&P.png', 'F', 'J', 'Ragdoll', 'M', 'Bege', 'C', 'E', NULL, NULL, 'G'),
(199, 'utilizador514@gmail.com', 'animal198', 'gatosA&P.png', 'M', 'A', 'ScottishFold', 'G', 'Preto', 'M', 'E', NULL, NULL, 'G'),
(200, 'utilizador514@gmail.com', 'animal199', 'gatosA&P.png', 'F', 'B', 'Outro', 'I', 'Cinzento', 'L', 'E', NULL, NULL, 'G')
